#!/bin/bash
#
# watcher.sh
# 
# Mette sotto monitoraggio una lista di directory specificate in "inotify_watched.lst"
# per eventi di creazione e modifica di qualunque file in esse contenuto (senza ricorsione).
# Intercetta quindi gli eventi generati da inotifywait e li decodifica per stabilire
# un opportuno trattamento per ogni tipo di file in ciascuna directory.
#
# Determina la directory di lavoro
DR=$(pwd)
BN=$(basename $0)
#
# input file
FF=$DR/inotify_watched.lst
#
# logfile
LF=$DR/$(date +%Y%m%d)_${BN}.log
echo "Avvio $BN dentro $DR..." >$LF
#
# ciclo principale
CMD=""
inotifywait -m -e close_write,moved_to --format '%T %e %w %f' --timefmt '%Y%m%d-%H%M' -q --syslog --fromfile $FF |
while read -r TIMESTAMP EVENT DIR FILE; do
	case "$DIR" in
		$HOME/.minecraft/versions/1.15.2/)
			case "$FILE" in
				1.15.2-natives-*/)
					# scopiazziamoci tutto sopra!
					echo "$TIMESTAMP ($EVENT): cp" >>$LF
					cp ./lwjgl3arm32/* $HOME/.minecraft/versions/1.15.2/${FILE}/
					;;
				*)
					echo "$TIMESTAMP ($EVENT): Unknown file: ${DIR}${FILE}" >>$LF
					;;
			esac
			;;
		*)
			echo "$TIMESTAMP ($EVENT): Unmanaged directory: $DIR" >>$LF
			;;
	esac
done
